version: '3.7'

services:

  db:
    image: mysql/mysql-server:8.0
    container_name: mysql
    #command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      #MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_HOST: '${DB_ROOT_HOST}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./database/mysql:/var/lib/mysql
    ports:
      - '${DB_PORT}:3306'
    networks:
      - database

networks:
  database:
    driver: bridge
