version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - backend
    command: --default-authentication-plugin=mysql_native_password

volumes:
  dbdata:


networks:
  backend:
    driver: bridge
